Repository rastle-dev/rastle-frontend, pull requests merged in 2023-12, with the labels that each got.

#25 RD-38 PG사 결제시스템 연동 (네이버,카카오,NICE) 테스트 서비스 구현
  package.json
  portone.d.ts
  src/components/Manager/product/UpdateProduct.tsx
  src/hooks/useOrder.tsx
  src/hooks/useProduct.tsx
  src/pages/_document.tsx
  src/pages/order/index.tsx
  yarn.lock
Labels: Feat

#26 RD-48 주문생성 API 기능 구현
  src/api/config.ts
  src/api/shop.ts
  src/components/Manager/product/UpdateProduct.tsx
  src/components/Mypage/cart.tsx
  src/hooks/manager/product/useCreateProduct.tsx
  src/hooks/manager/product/useUpdateProduct.tsx
  src/hooks/useMypage.tsx
  src/hooks/useProduct.tsx
  src/pages/_document.tsx
  src/pages/order/index.tsx
  src/pages/product/index.tsx
  src/pages/shop/index.tsx
Labels: Feat

#27 RD-50 세션만료 다이얼로그, 중복클릭 방지, 로딩바/스페너 디자인, 마이페이지 뒤로가기,전체상품주문 구현
  src/components/LoadingBar/index.tsx
  src/components/Mypage/cart.tsx
  src/components/Mypage/loginInfo.tsx
  src/components/common/Dialog/index.tsx
  src/hooks/useMypage.tsx
  src/hooks/useProduct.tsx
  src/pages/mypage/index.tsx
  src/pages/order/index.tsx
  src/pages/product/index.tsx
Labels: Feat, Design

#28 RD-51 무한스크롤
  src/api/shop.ts
  src/components/LoadingBar/index.tsx
  src/components/LoadingSpinner/index.tsx
  src/components/Shop/CodyProduct.tsx
  src/hooks/useShop.tsx
Labels: Feat, Refactor

#29 RD-52 이벤트 API 기능 구현, 새로고침 이슈 해결
  src/api/shop.ts
  src/components/LoadingBar/index.tsx
  src/components/Mypage/cart.tsx
  src/components/Mypage/loginInfo.tsx
  src/hooks/useProduct.tsx
  src/hooks/useShop.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/product/index.tsx
  src/pages/shop/index.tsx
Labels: Feat
