Repository rastle-dev/rastle-frontend, pull requests merged in 2024-03, with the labels that each got.

#44 RD-69 상세페이지 이미지 최적화 및 SEO 2차 최적화
  src/components/Home/EventProductLayer.tsx
  src/components/Home/ProductLayer.tsx
  src/components/ItemElement/index.tsx
  src/components/Shop/CategoryView/Cody/codySwiper.tsx
  src/components/Shop/CategoryView/Cody/index.tsx
  src/components/Shop/CategoryView/index.tsx
  src/components/Shop/DisplaySelectProduct.tsx
  src/components/Swiper/ImageSliderPage.tsx
  src/components/Swiper/index.tsx
  src/hooks/useProduct.tsx
  src/hooks/useShop.tsx
  src/interface/itemElement.ts
  src/pages/event/index.tsx
  src/pages/index.tsx
  src/pages/product/index.tsx
  src/pages/shop/index.tsx
  src/styles/product/index.styles.tsx
Labels: Feat, Refactor

#45 RD-71 스토리북 배포 자동화
  .github/workflows/chromatic.yml
  build-storybook.log
  package.json
  public/example_1.png
  public/example_2.png
  src/components/Common/Button/index.stories.tsx
  src/components/Common/ColorButton/index.stories.tsx
  src/components/Common/Dialog/index.stories.tsx
Labels: Config

#46 RD-72 Cypress 설치 및 깃 액션 연동 + 로그인 e2e 테스트코드 구현
  .github/workflows/cypress.yml
  .gitignore
  cypress.config.ts
  cypress/e2e/1-login/login.spec.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package.json
  src/components/Common/Button/index.tsx
  src/components/Common/ColorButton/index.tsx
  src/pages/product/index.tsx
  tsconfig.json
Labels: Feat, Config

#47 RD-73 장바구니, 결제 사전 검증 e2e 테스트코드 구현
  cypress/e2e/2-cart/cart.spec.cy.ts
  cypress/e2e/3-purchase/purchase.spec.cy.ts
  cypress/fixtures/cartProduct.json
  cypress/fixtures/cartProducts.json
  cypress/fixtures/coupon.json
  cypress/fixtures/defaultAddress.json
  cypress/fixtures/directProduct.json
  cypress/fixtures/emptyCart.json
  cypress/fixtures/imp47805780.json
  cypress/fixtures/memberInfo.json
  cypress/fixtures/preparePayment.json
  cypress/fixtures/productDetail.json
  cypress/fixtures/products.json
  cypress/fixtures/virtualCartOrder.json
  cypress/fixtures/virtualDirectOrder.json
  cypress/support/commands.ts
  src/api/shop.ts
  src/components/Common/IconButton/index.tsx
  src/components/Layout/MainHeader/index.tsx
  src/components/Mypage/Cart.tsx
  src/hooks/mypage/useMypage.ts
  src/hooks/useOrder.tsx
  src/pages/mypage/index.tsx
Labels: Feat

#48 RD-74 응모 관련 오류 및 SSR 이슈 해결
  src/api/cart.ts
  src/components/Event/EnterEventModal.tsx
  src/components/Home/EventProductLayer.tsx
  src/components/Mypage/Cart.tsx
  src/components/Mypage/Coupon.tsx
  src/components/Mypage/DefaultAddress.tsx
  src/components/Mypage/LoginInfo.tsx
  src/components/Mypage/OrderHistory.tsx
  src/hooks/mypage/orderList/useEventHistory.ts
  src/hooks/mypage/orderList/useOrderHistory.ts
  src/pages/event/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/shop/index.tsx
  src/styles/mypage/orderList/index.styles.tsx
Labels: bug, Refactor

#50 RD-77 결제연동 오류 해결, 응모내역상세조회 구현
  src/api/admin.ts
  src/api/index.ts
  src/api/shop.ts
  src/components/Event/EnterUpdateEventModal.tsx
  src/components/Event/EventHistory.tsx
  src/components/Home/ProductLayer.tsx
  src/components/Home/TopLayer.tsx
  src/components/Manager/OrderManagement.tsx
  src/components/Manager/UserManagement.tsx
  src/components/Shop/CategoryView/index.tsx
  src/components/Swiper/index.tsx
  src/constants/querykey.ts
  src/hooks/manager/bundle/useUpdateBundle.tsx
  src/hooks/manager/order/useOrderInfo.tsx
  src/hooks/manager/product/useUpdateEventProduct.tsx
  src/hooks/manager/product/useUpdateProduct.tsx
  src/hooks/mypage/cart/useCart.ts
  src/hooks/useOrder.tsx
  src/hooks/useOrderDetail.tsx
  src/hooks/useProduct.tsx
  src/hooks/useSignup.tsx
  src/pages/manager/index.tsx
  src/pages/orderDetail/index.tsx
  src/pages/product/index.tsx
  src/pages/shopinfo/guide/index.tsx
  src/pages/signup/index.tsx
  src/styles/index/index.styles.tsx
  src/styles/mypage/loginInfo/index.styles.tsx
  src/styles/mypage/orderList/index.styles.tsx
  src/styles/order/index.styles.tsx
  src/styles/product/index.styles.tsx
  src/styles/signup/index.styles.tsx
Labels: Feat
