Repository rastle-dev/rastle-frontend, pull requests merged in 2024-01, with the labels that each got.

#30 RD-53 타입 수정, 전역 인터페이스 선언, 컴포넌트 기능 정리 및 훅 분리 작업
  src/api/auth.ts
  src/api/cart.ts
  src/components/ItemElement/index.tsx
  src/components/Mypage/cart.tsx
  src/components/Mypage/defaultAddress.tsx
  src/components/Mypage/loginInfo.tsx
  src/components/Mypage/orderList.tsx
  src/components/Shop/CategoryTab/index.tsx
  src/components/Shop/CodyProduct.tsx
  src/components/Shop/DisplaySelectProduct.tsx
  src/hooks/mypage/cart/useCart.ts
  src/hooks/mypage/loginInfo/useLoginInfo.ts
  src/hooks/mypage/useMypage.ts
  src/hooks/useDialog.tsx
  src/hooks/useLogin.tsx
  src/hooks/useMypage.tsx
  src/hooks/useOrder.tsx
  src/hooks/useProduct.tsx
  src/hooks/useScroll.tsx
  src/hooks/useShop.tsx
  src/interface/cartProductItem.ts
  src/interface/category.ts
  src/interface/itemElement.ts
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/order/index.tsx
  src/pages/product/index.tsx
  src/pages/shop/index.tsx
  src/styles/login/index.styles.tsx
  src/styles/mypage/cart/index.styles.tsx
  src/styles/mypage/loginInfo/index.styles.tsx
  src/styles/shop/index.styles.tsx
Labels: Feat, Refactor

#31 RD-54 메인페이지,SHOP페이지 디렉토리 및 코드 분리
  src/components/Common/Button/index.stories.tsx
  src/components/Common/Button/index.tsx
  src/components/Common/ColorButton/index.stories.tsx
  src/components/Common/ColorButton/index.tsx
  src/components/Common/Dialog/index.stories.tsx
  src/components/Common/Dialog/index.tsx
  src/components/Common/Icon/index.stories.tsx
  src/components/Common/Icon/index.tsx
  src/components/Common/IconButton/index.stories.tsx
  src/components/Common/IconButton/index.styles.tsx
  src/components/Common/IconButton/index.tsx
  src/components/Common/Input/index.stories.tsx
  src/components/Common/Input/index.tsx
  src/components/Home/EventProductLayer.tsx
  src/components/Home/ProductLayer.tsx
  src/components/Home/TopLayer.tsx
  src/components/Layout/MainHeader/index.styles.tsx
  src/components/Manager/bundle/CreateBundle.tsx
  src/components/Manager/bundle/UpdateBundle.tsx
  src/components/Manager/category/CreateCategory.tsx
  src/components/Manager/category/UpdateCategory.tsx
  src/components/Manager/event/CreateEvent.tsx
  src/components/Manager/event/UpdateEvent.tsx
  src/components/Manager/product/CreateEventProduct.tsx
  src/components/Manager/product/CreateProduct.tsx
  src/components/Manager/product/UpdateEventProduct.tsx
  src/components/Manager/product/UpdateProduct.tsx
  src/components/Mypage/loginInfo.tsx
  src/components/Shop/CategoryView/Cody/codySwiper.tsx
  src/components/Shop/CategoryView/Cody/index.tsx
  src/components/Shop/CategoryView/index.tsx
  src/components/Swiper/index.tsx
  src/hooks/useShop.tsx
  src/pages/guest/index.tsx
  src/pages/index.tsx
  src/pages/order/index.tsx
  src/pages/product/index.tsx
  src/pages/shop/index.tsx
  src/pages/signup/index.tsx
  src/styles/index/index.styles.tsx
  src/styles/login/index.styles.tsx
  src/styles/mypage/cart/index.styles.tsx
  src/styles/mypage/index.styles.tsx
  src/styles/mypage/loginInfo/index.styles.tsx
  src/styles/order/index.styles.tsx
  src/styles/orderconfirm/index.styles.tsx
  src/styles/product/index.styles.tsx
  src/styles/signup/index.styles.tsx
Labels: bug, Refactor

#32 RD-55 쿠폰 팝업창 및 쿠폰페이지 UI,기능 구현
  public/image/LOGO_WHITE.png
  public/image/coupon.png
  src/api/cart.ts
  src/api/config.ts
  src/components/Home/SignupPopup/index.styles.tsx
  src/components/Home/SignupPopup/index.tsx
  src/components/Mypage/coupon.tsx
  src/components/Shop/CategoryView/index.tsx
  src/constants/icon.ts
  src/constants/querykey.ts
  src/hooks/mypage/coupon/useCoupon.ts
  src/hooks/mypage/useMypage.ts
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/styles/mypage/cart/index.styles.tsx
  src/styles/mypage/coupon/index.styles.tsx
  src/styles/mypage/index.styles.tsx
Labels: Feat, Design

#34 RD-57 장바구니 수정 및 소셜로그인 오류
  next.config.js
  package.json
  src/components/Mypage/cart.tsx
  src/hooks/mypage/cart/useCart.ts
  src/interface/cartProductItem.ts
  src/pages/index.tsx
  src/styles/mypage/cart/index.styles.tsx
  src/styles/mypage/index.styles.tsx
Labels: Feat, Design, Refactor

#35 RD-58 주문내역 UI 및 기능 구현
  src/api/cart.ts
  src/components/Mypage/cart.tsx
  src/components/Mypage/orderList.tsx
  src/constants/querykey.ts
  src/hooks/mypage/cart/useCart.ts
  src/hooks/mypage/orderList/useOrderList.ts
  src/styles/mypage/orderList/index.styles.tsx
Labels: Feat

#36 RD-59 에러경계(Error boundaries)설정 및 페이지 구현
  src/components/ErrorBoundary.tsx
  src/pages/_app.tsx
Labels: Feat

#37 RD-60 기본 배송지 UI 및 기능 구현 + 타임아웃 기능 커스텀 훅 분리
  src/api/cart.ts
  src/api/config.ts
  src/components/Mypage/cart.tsx
  src/components/Mypage/coupon.tsx
  src/components/Mypage/defaultAddress.tsx
  src/components/Mypage/loginInfo.tsx
  src/components/Mypage/orderList.tsx
  src/components/Shop/CategoryView/index.tsx
  src/constants/querykey.ts
  src/hooks/manager/user/useUserInfo.tsx
  src/hooks/mypage/cart/useCart.ts
  src/hooks/mypage/coupon/useCoupon.ts
  src/hooks/mypage/defaultAddress/useDefaultAddress.ts
  src/hooks/mypage/orderList/useOrderList.ts
  src/hooks/useLoadingWithTimeout.ts
  src/hooks/useOrder.tsx
  src/pages/order/index.tsx
  src/pages/shop/index.tsx
  src/styles/mypage/defaultAddress/index.styles.tsx
Labels: Feat

#38 RD-63 사전검증/사후검증 구현
  portone.d.ts
  src/api/cart.ts
  src/api/config.ts
  src/api/shop.ts
  src/components/Common/Icon/index.stories.tsx
  src/components/Common/Icon/index.tsx
  src/components/Common/IconButton/index.tsx
  src/components/Swiper/index.tsx
  src/constants/icon.ts
  src/constants/querykey.ts
  src/hooks/useOrder.tsx
  src/pages/order/index.tsx
  src/pages/orderConfirm/index.tsx
  src/pages/product/index.tsx
  src/pages/shop/index.tsx
  src/styles/order/index.styles.tsx
Labels: Feat

#39 RD-62 이벤트페이지 UI 및 기능 구현
  package.json
  src/api/config.ts
  src/api/shop.ts
  src/components/Common/Button/index.tsx
  src/components/Common/Input/index.tsx
  src/components/Common/Modal/index.tsx
  src/components/Event/CountDownTimer.tsx
  src/components/Event/EnterEventModal.tsx
  src/components/ItemElement/index.tsx
  src/components/Layout/MainHeader/index.tsx
  src/components/Mypage/orderList.tsx
  src/components/Shop/CategoryView/Cody/codySwiper.tsx
  src/components/Shop/CategoryView/index.tsx
  src/constants/path.ts
  src/hooks/mypage/orderList/useOrderList.ts
  src/hooks/useLogin.tsx
  src/hooks/useProduct.tsx
  src/hooks/useSignup.tsx
  src/interface/itemElement.ts
  src/pages/event/index.tsx
  src/pages/order/index.tsx
  src/pages/product/index.tsx
  src/pages/shop/index.tsx
  src/pages/signup/index.tsx
  src/stores/atom/recoilState.ts
  src/styles/product/index.styles.tsx
Labels: Feat, Refactor
